# 五、ndarray的矩阵操作

## 加减乘除

In [1]:
import numpy as np
import random

In [3]:
n = np.random.randint(0,100,size=(6,6))
n

array([[83,  1,  6, 85, 44, 29],
       [87, 81, 52, 93, 97, 29],
       [75, 88, 58, 99, 77, 64],
       [45, 76, 36, 83, 95, 91],
       [ 2, 21, 36, 71, 53, 18],
       [14, 25, 28, 22, 48, 56]])

In [7]:
n2 = n+1#每个元素和1相加

In [9]:
5*n2

array([[420,  10,  35, 430, 225, 150],
       [440, 410, 265, 470, 490, 150],
       [380, 445, 295, 500, 390, 325],
       [230, 385, 185, 420, 480, 460],
       [ 15, 110, 185, 360, 270,  95],
       [ 75, 130, 145, 115, 245, 285]])

In [10]:
np.dot(n,n2)

array([[11993,  9049,  6602, 18807, 16258, 13219],
       [23392, 21493, 15841, 35759, 31496, 20472],
       [24197, 23509, 16979, 35854, 33321, 22879],
       [18672, 20373, 15692, 30519, 29838, 20598],
       [ 8447, 12031,  8361, 15940, 15516, 11595],
       [ 7500,  8776,  7289, 12946, 12712,  9118]])

# 六、ndarray的排序

In [14]:
#排序只对1维数组有意义
def select_sort(arr):
    for i in range(0,len(arr)-1):
        index = np.argmin(arr[i:])+i
        if arr[i] > arr[index]:
            arr[i],arr[index] = arr[index],arr[i]
    return arr

In [15]:
n = np.array([234,23,545,678,2132,78,123])
select_sort(n)

array([  23,   78,  123,  234,  545,  678, 2132])