## 切分

In [1]:
import random
import numpy as np
import matplotlib.pyplot as plt

In [3]:
n=np.random.randint(0,100,size=(6,6))
n

array([[16, 98, 92, 44, 43, 20],
       [60, 78, 53, 38, 52, 37],
       [18, 79, 14,  7, 61, 36],
       [32, 99, 39, 18, 48, 78],
       [34, 94, 64, 57, 27, 37],
       [24, 80,  9, 46, 34, 29]])

In [5]:
#左闭右开，axis=0表示对行进行切割，axis=1表示对列进行切割
np.split(n,[2,4],axis=0)

[array([[16, 98, 92, 44, 43, 20],
        [60, 78, 53, 38, 52, 37]]),
 array([[18, 79, 14,  7, 61, 36],
        [32, 99, 39, 18, 48, 78]]),
 array([[34, 94, 64, 57, 27, 37],
        [24, 80,  9, 46, 34, 29]])]

## 副本

In [8]:
#所有赋值运算不会为ndarray的任何元素创建副本，对赋值后的对象的操作也对原来的对象生效
n_copy = n.copy()
n_copy

array([[16, 98, 92, 44, 43, 20],
       [60, 78, 53, 38, 52, 37],
       [18, 79, 14,  7, 61, 36],
       [32, 99, 39, 18, 48, 78],
       [34, 94, 64, 57, 27, 37],
       [24, 80,  9, 46, 34, 29]])

# ndarray的聚合操作

## 1.求和

In [11]:
n.sum()#axis=None 表示所有的维度都聚合成0

1695

In [14]:
n.sum(axis=0)#每一列聚合

array([184, 528, 271, 210, 265, 237])

In [15]:
n.sum(axis=1)#行的聚合

array([313, 318, 215, 314, 313, 222])

In [16]:
n.min(axis=0)

array([16, 78,  9,  7, 27, 20])

In [13]:
n.max()

99

In [18]:
n.argmax(axis=0)#列的最大值的索引

array([1, 3, 0, 4, 2, 3], dtype=int64)

In [21]:
n.any()

True

In [22]:
n.all()

True

In [26]:
np.nansum(n)#如果array里面有nan则用sum算不了，需要用np.nansum()计算

1695

In [27]:
import pandas as pd

In [33]:
heights=pd.read_csv('.\president_heights.csv')

In [34]:
#data frame
heights

order                    name  height(cm)
0       1       George Washington         189
1       2              John Adams         170
2       3        Thomas Jefferson         189
3       4           James Madison         163
4       5            James Monroe         183
5       6       John Quincy Adams         171
6       7          Andrew Jackson         185
7       8        Martin Van Buren         168
8       9  William Henry Harrison         173
9      10              John Tyler         183
10     11           James K. Polk         173
11     12          Zachary Taylor         173
12     13        Millard Fillmore         175
13     14         Franklin Pierce         178
14     15          James Buchanan         183
15     16         Abraham Lincoln         193
16     17          Andrew Johnson         178
17     18        Ulysses S. Grant         173
18     19     Rutherford B. Hayes         174
19     20       James A. Garfield         183
20     21       Chester A. Arthur         183
21     23       Benjamin Harrison         168
22     25        William McKinley         170
23     26      Theodore Roosevelt         178
24     27     William Howard Taft         182
25     28          Woodrow Wilson         180
26     29       Warren G. Harding         183
27     30         Calvin Coolidge         178
28     31          Herbert Hoover         182
29     32   Franklin D. Roosevelt         188
30     33         Harry S. Truman         175
31     34    Dwight D. Eisenhower         179
32     35         John F. Kennedy         183
33     36       Lyndon B. Johnson         193
34     37           Richard Nixon         182
35     38             Gerald Ford         183
36     39            Jimmy Carter         177
37     40           Ronald Reagan         185
38     41       George H. W. Bush         188
39     42            Bill Clinton         188
40     43          George W. Bush         182
41     44            Barack Obama         185

In [45]:
data=heights['height(cm)'].values

In [48]:
#美国历任总统平均身高
data.mean()

179.73809523809524

In [52]:
#标准方差
data.std()

6.931843442745892

In [49]:
names=heights['name']

In [50]:
names

0          George Washington
1                 John Adams
2           Thomas Jefferson
3              James Madison
4               James Monroe
5          John Quincy Adams
6             Andrew Jackson
7           Martin Van Buren
8     William Henry Harrison
9                 John Tyler
10             James K. Polk
11            Zachary Taylor
12          Millard Fillmore
13           Franklin Pierce
14            James Buchanan
15           Abraham Lincoln
16            Andrew Johnson
17          Ulysses S. Grant
18       Rutherford B. Hayes
19         James A. Garfield
20         Chester A. Arthur
21         Benjamin Harrison
22          William McKinley
23        Theodore Roosevelt
24       William Howard Taft
25            Woodrow Wilson
26         Warren G. Harding
27           Calvin Coolidge
28            Herbert Hoover
29     Franklin D. Roosevelt
30           Harry S. Truman
31      Dwight D. Eisenhower
32           John F. Kennedy
33         Lyndon B. Johnson
34            