In [1]:
import random
import numpy as np
import pandas as pd

In [2]:
n1 = np.random.randint(0,100,size=(3,3))
n2 = np.random.randint(0,100,size=(3,3))
display(n1,n2)

array([[13, 57, 48],
       [96, 33, 92],
       [49, 47, 95]])

array([[ 0,  5, 73],
       [35, 52, 93],
       [50, 28,  6]])

In [3]:
np.concatenate((n1,n2),axis=1)

array([[13, 57, 48,  0,  5, 73],
       [96, 33, 92, 35, 52, 93],
       [49, 47, 95, 50, 28,  6]])

In [4]:
np.hstack((n1,n2))

array([[13, 57, 48,  0,  5, 73],
       [96, 33, 92, 35, 52, 93],
       [49, 47, 95, 50, 28,  6]])

In [5]:
np.vstack((n1,n2))

array([[13, 57, 48],
       [96, 33, 92],
       [49, 47, 95],
       [ 0,  5, 73],
       [35, 52, 93],
       [50, 28,  6]])

In [ ]:
#生成DataFrame
def make_df(index,columns):
    df = D